### ISSUE TITLE
loading simple-date changes result

### ISSUE THREAD

**Issue by aarvid** [fukamachi/cl-dbi#23] opened 2015-09-10 14:29 UTC
loading postmodern's simple-date causes query results to change type. 

Is this behavior intended? I find no explicit reference to simple-date in the source using grep.

    CL-USER> (ql:quickload :cl-dbi)
    To load "cl-dbi":
      Load 1 ASDF system:
	cl-dbi
    ; Loading "cl-dbi"

    (:CL-DBI)
    CL-USER> (dbi:with-connection (conn :postgres
			       :database-name "dbtullius"
			       :username "utullius"
			       :password "**")
      (let* ((query (dbi:prepare conn
				 "SELECT current_date, interval '1 month'"))
	     (result (dbi:execute query)))
	(dbi:fetch result)))
    To load "dbd-postgres":
      Load 1 ASDF system:
	dbd-postgres
    ; Loading "dbd-postgres"

    (:|date| 3650832000 :|interval|
     ((:MONTHS 1) (:DAYS 0) (:SECONDS 0) (:USECONDS 0)))
    CL-USER> (ql:quickload :simple-date)
    To load "simple-date":
      Load 1 ASDF system:
	simple-date
    ; Loading "simple-date"

    (:SIMPLE-DATE)
    CL-USER> (dbi:with-connection (conn :postgres
			       :database-name "dbtullius"
			       :username "utullius"
			       :password "**")
      (let* ((query (dbi:prepare conn
				 "SELECT current_date, interval '1 month'"))
	     (result (dbi:execute query)))
	(dbi:fetch result)))
    (:|date| #<SIMPLE-DATE:DATE 10-09-2015> :|interval| #<SIMPLE-DATE:INTERVAL P1M>)
    CL-USER>

**Comment by aarvid** [comment] 2015-09-10 14:43
Sorry again. I did not realize you were using cl-postgres of postmodern. this is a postmodern issue.

**Comment by aarvid** [comment] 2015-09-10 14:56
You should really document the fact that the postgres driver uses cl-postgres of postmodern.  Postmodern and cl-postgres is well documented.

**Comment by fukamachi** [comment] 2015-09-10 16:32
It's intended since it's an intended behaviour of simple-date. Closing.

**Closed by fukamachi** 2015-09-10 16:32 UTC
